import { createContext, useContext, useState, useEffect } from "react";

import MeatB from "./asests/MeatBurger.png";
import CheeseB from "./asests/CheeseBurger.png";
import ItaliaB from "./asests/ItaliaBurger.png";
import HotB from "./asests/HotBurger.png";
import BarbekuB from "./asests/BarbekuBurger.png";
import VeganB from "./asests/VeganBurger.png";

import Kfree from "./asests/Kfree.png";
import Nacho from "./asests/Nacho.png";
import Onion from "./asests/Onion.png";
import Nagets from "./asests/Naggets.png";
import sir from "./asests/SIRNYE.png";

const MyContext = createContext();

export const MyProvider = ({ children }) => {
  const [MenuMassiv, setMenuMassiv] = useState([
    {
      id: 1,
      quantity: 1,
      img: MeatB,
      name: "Мясная бомба",
      category: "Бургеры",
      price: "689₽",
      Gram: "520г",
      desc: "Супер мясное наслаждение! Большая рубленая котлета из свежего говяжего мяса покорит вас своей сочностью, а хрустящие листья салата добавят свежести.",
      PrIncludes1: "Пшеничная булочка",
      PrIncludes1: "Котлета из говядины",
      PrIncludes1: "Красный лук",
      PrIncludes1: "Листья салата",
      PrIncludes1: "Соус горчичный",
    },
    {
      id: 2,
      quantity: 1,
      img: CheeseB,
      name: "Сырный кинг",
      category: "Бургеры",
      price: "759₽",
      Gram: "450г",
      desc: "Горячий бургер с плавленым сыром, беконом и соусом BBQ. Идеальный выбор для любителей сыра и мясных деликатесов.",
      PrIncludes1: "Котлета из говядины",
      PrIncludes1: "Плавленый сыр",
      PrIncludes1: "Бекон",
      PrIncludes1: "Лук карамелизированный",
      PrIncludes1: "Соус BBQ",
    },
    {
      id: 3,
      quantity: 1,
      img: ItaliaB,
      name: "Итальянский",
      category: "Бургеры",
      price: "829₽",
      Gram: "530г",
      desc: "Острый бургер с пикантной чипотле-коралловой котлетой, остреньким соусом и маринованным перцем. Для настоящих ценителей острого.",
      PrIncludes1: "Булочка с кунжутом",
      PrIncludes1: "Котлета с чипотле",
      PrIncludes1: "Маринованный перец",
      PrIncludes1: "Сыр пекорино",
      PrIncludes1: "Соус чипотле",
    },
    {
      id: 4,
      quantity: 1,
      img: HotB,
      name: "Острый перчик",
      category: "Бургеры",
      price: "669₽",
      Gram: "490г",
      desc: "Бургер с остренькой котлетой и халапеньо, приправленный соусом чили. Подойдет для тех, кто любит острые ощущения.",
      PrIncludes1: "Котлета из говядины",
      PrIncludes1: "Халапеньо",
      PrIncludes1: "Лук красный",
      PrIncludes1: "Сыр чеддер",
      PrIncludes1: "Соус чили",
    },
    {
      id: 5,
      quantity: 1,
      img: BarbekuB,
      name: "Барбекю классик",
      category: "Бургеры",
      price: "699₽",
      Gram: "480г",
      desc: "Классический бургер с котлетой из говядины, хрустящим луком и острым соусом барбекю. Идеально для настоящих гурманов.",
      PrIncludes1: "Котлета из говядины",
      PrIncludes1: "Хрустящий лук",
      PrIncludes1: "Помидоры",
      PrIncludes1: "Листья салата",
      PrIncludes1: "Соус барбекю",
    },
    {
      id: 6,
      quantity: 1,
      img: VeganB,
      name: "Вегги-лайк",
      category: "Бургеры",
      price: "639₽",
      Gram: "400г",
      desc: "Для вегетарианцев — котлета из черных бобов с авокадо, помидорами и свежими овощами. Легкий и полезный выбор.",
      PrIncludes1: "Булочка без глютена",
      PrIncludes1: "Котлета из черных бобов",
      PrIncludes1: "Авокадо",
      PrIncludes1: "Помидоры",
      PrIncludes1: "Огурцы",
      PrIncludes1: "Соус на основе йогурта",
    },
    {
      id: 7,
      quantity: 1,
      img: Kfree,
      name: "Картошка фри",
      category: "Закуски",
      price: "249₽",
      Gram: "250г",
      desc: "Хрустящая картошка фри, обжаренная до золотистой корочки. Идеально подходит для перекуса или в качестве гарнира.",
      PrIncludes1: "Картофель",
      PrIncludes2: "Соль",
      PrIncludes3: "Масло растительное",
    },
    {
      id: 8,
      quantity: 1,
      img: Nagets,
      name: "Наггетсы",
      category: "Закуски",
      price: "359₽",
      Gram: "200г",
      desc: "Хрустящие куриные наггетсы, приготовленные в панировке. Подаются с соусом на выбор.",
      PrIncludes1: "Куриное филе",
      PrIncludes2: "Панировка",
      PrIncludes3: "Соус на выбор",
    },
    {
      id: 9,
      quantity: 1,
      img: Onion,
      name: "Кольца лука",
      category: "Закуски",
      price: "299₽",
      Gram: "180г",
      desc: "Хрустящие кольца лука, обжаренные до золотистого цвета. Отличная закуска к основным блюдам.",
      PrIncludes1: "Лук",
      PrIncludes2: "Панировка",
      PrIncludes3: "Масло растительное",
    },
    {
      id: 10,
      quantity: 1,
      img: sir,
      name: "Сырные палочки",
      category: "Закуски",
      price: "399₽",
      Gram: "150г",
      desc: "Палочки из расплавленного сыра, обжаренные до хрустящей корочки. Подаются с соусом для макания.",
      PrIncludes1: "Сыр",
      PrIncludes2: "Панировка",
      PrIncludes3: "Соус для макания",
    },
    {
      id: 11,
      quantity: 1,
      img: Onion,
      name: "Стики из моцареллы",
      category: "Закуски",
      price: "379₽",
      Gram: "200г",
      desc: "Обжаренные до хрустящей корочки стики из сыра моцарелла. Внутри тянущийся сыр, а снаружи — золотистая корочка.",
      PrIncludes1: "Сыр моцарелла",
      PrIncludes2: "Панировка",
      PrIncludes3: "Масло растительное",
    },
    {
      id: 12,
      quantity: 1,
      img: Nacho,
      name: "Начос",
      category: "Закуски",
      price: "329₽",
      Gram: "180г",
      desc: "Сочные рулеты с начинкой из свежих овощей и рисовой бумаги. Подаются с соусом на основе арахисовой пасты.",
      PrIncludes1: "Рисовая бумага",
      PrIncludes3: "Соус на основе арахисовой пасты",
    },
    {
      id: 13,
      quantity: 1,
      img: "ClassicHotDog",
      name: "Классический хот-дог",
      category: "Хот-доги",
      price: "299₽",
      Gram: "150г",
      desc: "Классический хот-дог с сосиской в булочке. Подается с горчицей и кетчупом.",
      PrIncludes1: "Булочка",
      PrIncludes2: "Сосиска",
      PrIncludes3: "Горчица",
      PrIncludes4: "Кетчуп",
    },
    {
      id: 14,
      quantity: 1,
      img: "CheeseHotDog",
      name: "Хот-дог с сыром",
      category: "Хот-доги",
      price: "349₽",
      Gram: "200г",
      desc: "Хот-дог с сосиской, плавленым сыром и карамелизированным луком. Подается с горчицей и кетчупом.",
      PrIncludes1: "Булочка",
      PrIncludes2: "Сосиска",
      PrIncludes3: "Плавленый сыр",
      PrIncludes4: "Карамелизированный лук",
      PrIncludes5: "Горчица",
      PrIncludes6: "Кетчуп",
    },
    {
      id: 15,
      quantity: 1,
      img: "SpicyHotDog",
      name: "Острый хот-дог",
      category: "Хот-доги",
      price: "359₽",
      Gram: "180г",
      desc: "Хот-дог с острой сосиской, соусом чили и халапеньо. Для любителей острого.",
      PrIncludes1: "Булочка",
      PrIncludes2: "Острая сосиска",
      PrIncludes3: "Соус чили",
      PrIncludes4: "Халапеньо",
    },
    {
      id: 16,
      quantity: 1,
      img: "BBQHotDog",
      name: "Хот-дог в BBQ соусе",
      category: "Хот-доги",
      price: "339₽",
      Gram: "200г",
      desc: "Хот-дог с сосиской, BBQ соусом и хрустящим беконом. Подается с маринованными огурцами.",
      PrIncludes1: "Булочка",
      PrIncludes2: "Сосиска",
      PrIncludes3: "BBQ соус",
      PrIncludes4: "Бекон",
      PrIncludes5: "Маринованные огурцы",
    },
    {
      id: 17,
      quantity: 1,
      img: "VeggieHotDog",
      name: "Вегетарианский хот-дог",
      category: "Хот-доги",
      price: "329₽",
      Gram: "180г",
      desc: "Вегетарианский хот-дог с соевым наполнителем, свежими овощами и соусом на основе авокадо.",
      PrIncludes1: "Булочка",
      PrIncludes2: "Соевый наполнителем",
      PrIncludes3: "Авокадо",
      PrIncludes4: "Помидоры",
      PrIncludes5: "Огурцы",
      PrIncludes6: "Соус на основе авокадо",
    },
    {
      id: 18,
      quantity: 1,
      img: "MexicanHotDog",
      name: "Мексиканский хот-дог",
      category: "Хот-доги",
      price: "369₽",
      Gram: "200г",
      desc: "Хот-дог с сосиской, сальсой, гуакамоле и свежей кинзой. Острота и свежесть в одном флаконе.",
      PrIncludes1: "Булочка",
      PrIncludes2: "Сосиска",
      PrIncludes3: "Сальса",
      PrIncludes4: "Гуакамоле",
      PrIncludes5: "Свежая кинза",
    },
    {
      id: 19,
      quantity: 1,
      img: "ComboClassic",
      name: "Классическое комбо",
      category: "Комбо-меню",
      price: "799₽",
      Gram: "600г",
      desc: "Классическое комбо: бургер, картошка фри и напиток. Идеально для сытного обеда или ужина.",
      PrIncludes1: "Бургер с котлетой из говядины",
      PrIncludes2: "Картошка фри",
      PrIncludes3: "Напиток (на выбор: кола, спрайт, фанта)",
    },
    {
      id: 20,
      quantity: 1,
      img: "ComboCheese",
      name: "Комбо с сыром",
      category: "Комбо-меню",
      price: "899₽",
      Gram: "650г",
      desc: "Комбо с сыром: чизбургер, наггетсы и напиток. Отличный выбор для любителей сыра.",
      PrIncludes1: "Чизбургер",
      PrIncludes2: "Наггетсы (6 шт.)",
      PrIncludes3: "Напиток (на выбор: кола, спрайт, фанта)",
    },
    {
      id: 21,
      quantity: 1,
      img: "ComboSpicy",
      name: "Острое комбо",
      category: "Комбо-меню",
      price: "849₽",
      Gram: "600г",
      desc: "Острое комбо: острый бургер, кольца лука и напиток. Для тех, кто любит пикантные блюда.",
      PrIncludes1: "Острый бургер",
      PrIncludes2: "Кольца лука",
      PrIncludes3: "Напиток (на выбор: кола, спрайт, фанта)",
    },
    {
      id: 22,
      quantity: 1,
      img: "ComboVeggie",
      name: "Вегетарианское комбо",
      category: "Комбо-меню",
      price: "869₽",
      Gram: "650г",
      desc: "Вегетарианское комбо: вегги-бургер, весенние рулеты и напиток. Легкий и полезный выбор.",
      PrIncludes1: "Вегги-бургер",
      PrIncludes2: "Весенние рулеты",
      PrIncludes3: "Напиток (на выбор: кола, спрайт, фанта)",
    },
    {
      id: 23,
      quantity: 1,
      img: "ComboMexican",
      name: "Мексиканское комбо",
      category: "Комбо-меню",
      price: "929₽",
      Gram: "700г",
      desc: "Мексиканское комбо: мексиканский бургер, сырные палочки и напиток. Острота и вкус в одном наборе.",
      PrIncludes1: "Мексиканский бургер",
      PrIncludes2: "Сырные палочки",
      PrIncludes3: "Напиток (на выбор: кола, спрайт, фанта)",
    },
    {
      id: 24,
      quantity: 1,
      img: "ComboBBQ",
      name: "BBQ комбо",
      category: "Комбо-меню",
      price: "919₽",
      Gram: "700г",
      desc: "BBQ комбо: бургер в BBQ соусе, картошка фри и напиток. Для любителей насыщенных вкусов.",
      PrIncludes1: "Бургер в BBQ соусе",
      PrIncludes2: "Картошка фри",
      PrIncludes3: "Напиток (на выбор: кола, спрайт, фанта)",
    },
    {
      id: 25,
      quantity: 1,
      img: "ClassicShawarma",
      name: "Классическая шаурма",
      category: "Шаурма",
      price: "299₽",
      Gram: "250г",
      desc: "Классическая шаурма с сочным мясом курицы, свежими овощами и соусом. Идеально для быстрого перекуса.",
      PrIncludes1: "Куриное мясо",
      PrIncludes2: "Лаваш",
      PrIncludes3: "Помидоры",
      PrIncludes4: "Огурцы",
      PrIncludes5: "Лук",
      PrIncludes6: "Соус (чесночный, томатный или майонезный)",
    },
    {
      id: 26,
      quantity: 1,
      img: "BeefShawarma",
      name: "Шаурма с говядиной",
      category: "Шаурма",
      price: "349₽",
      Gram: "280г",
      desc: "Шаурма с говядиной, запеченной до сочности, с добавлением свежих овощей и пикантного соуса.",
      PrIncludes1: "Говяжье мясо",
      PrIncludes2: "Лаваш",
      PrIncludes3: "Помидоры",
      PrIncludes4: "Огурцы",
      PrIncludes5: "Лук",
      PrIncludes6: "Соус (сметанный или острый)",
    },
    {
      id: 27,
      quantity: 1,
      img: "VeggieShawarma",
      name: "Вегетарианская шаурма",
      category: "Шаурма",
      price: "319₽",
      Gram: "250г",
      desc: "Вегетарианская шаурма с обжаренными овощами и хумусом. Подходит для вегетарианцев и веганов.",
      PrIncludes1: "Обжаренные овощи (перец, баклажаны, кабачки)",
      PrIncludes2: "Лаваш",
      PrIncludes3: "Хумус",
      PrIncludes4: "Помидоры",
      PrIncludes5: "Огурцы",
      PrIncludes6: "Лук",
    },
    {
      id: 28,
      quantity: 1,
      img: "SpicyShawarma",
      name: "Острая шаурма",
      category: "Шаурма",
      price: "339₽",
      Gram: "270г",
      desc: "Острая шаурма с куриным мясом, острым соусом и свежими овощами. Для любителей пикантного вкуса.",
      PrIncludes1: "Куриное мясо",
      PrIncludes2: "Лаваш",
      PrIncludes3: "Помидоры",
      PrIncludes4: "Огурцы",
      PrIncludes5: "Лук",
      PrIncludes6: "Острый соус",
    },
    {
      id: 29,
      quantity: 1,
      img: "BBQShawarma",
      name: "Шаурма BBQ",
      category: "Шаурма",
      price: "359₽",
      Gram: "300г",
      desc: "Шаурма с куриным мясом в BBQ соусе, свежими овощами и хрустящими добавками.",
      PrIncludes1: "Куриное мясо в BBQ соусе",
      PrIncludes2: "Лаваш",
      PrIncludes3: "Помидоры",
      PrIncludes4: "Огурцы",
      PrIncludes5: "Лук",
      PrIncludes6: "Соус BBQ",
    },
    {
      id: 30,
      quantity: 1,
      img: "ChickenShawarmaWrap",
      name: "Шаурма-ролл с курицей",
      category: "Шаурма",
      price: "329₽",
      Gram: "260г",
      desc: "Шаурма-ролл с курицей, свежими овощами и соусом, завернутая в лаваш. Удобная для перекуса на ходу.",
      PrIncludes1: "Куриное мясо",
      PrIncludes2: "Лаваш",
      PrIncludes3: "Помидоры",
      PrIncludes4: "Огурцы",
      PrIncludes5: "Лук",
      PrIncludes6: "Соус (по выбору)",
    },
    {
      id: 31,
      quantity: 1,
      img: "MargheritaPizza",
      name: "Пицца Маргарита",
      category: "Пицца",
      price: "499₽",
      Gram: "400г",
      desc: "Классическая пицца Маргарита с томатным соусом, моцареллой и свежим базиликом. Простота и вкус в одном блюде.",
      PrIncludes1: "Тесто для пиццы",
      PrIncludes2: "Томатный соус",
      PrIncludes3: "Моцарелла",
      PrIncludes4: "Базилик",
    },
    {
      id: 32,
      quantity: 1,
      img: "PepperoniPizza",
      name: "Пицца Пепперони",
      category: "Пицца",
      price: "549₽",
      Gram: "450г",
      desc: "Пицца с насыщенным вкусом пепперони, томатным соусом и моцареллой. Отлично подходит для любителей острых вкусов.",
      PrIncludes1: "Тесто для пиццы",
      PrIncludes2: "Томатный соус",
      PrIncludes3: "Моцарелла",
      PrIncludes4: "Пепперони",
    },
    {
      id: 33,
      quantity: 1,
      img: "VegetarianPizza",
      name: "Вегетарианская пицца",
      category: "Пицца",
      price: "529₽",
      Gram: "400г",
      desc: "Пицца с обилием свежих овощей, моцареллой и оливковым маслом. Идеально для вегетарианцев и любителей здорового питания.",
      PrIncludes1: "Тесто для пиццы",
      PrIncludes2: "Томатный соус",
      PrIncludes3: "Моцарелла",
      PrIncludes4: "Свежие овощи (перец, помидоры, оливки, грибы)",
    },
    {
      id: 34,
      quantity: 1,
      img: "BBQChickenPizza",
      name: "Пицца с курицей BBQ",
      category: "Пицца",
      price: "569₽",
      Gram: "450г",
      desc: "Пицца с курицей в BBQ соусе, красным луком и корнишонами. Насыщенный вкус BBQ в каждом кусочке.",
      PrIncludes1: "Тесто для пиццы",
      PrIncludes2: "BBQ соус",
      PrIncludes3: "Моцарелла",
      PrIncludes4: "Куриное мясо",
      PrIncludes5: "Красный лук",
      PrIncludes6: "Корнишоны",
    },
    {
      id: 35,
      quantity: 1,
      img: "SeafoodPizza",
      name: "Пицца с морепродуктами",
      category: "Пицца",
      price: "599₽",
      Gram: "450г",
      desc: "Пицца с различными морепродуктами, такими как креветки, мидии и кальмары, в сочетании с кремовым соусом и моцареллой.",
      PrIncludes1: "Тесто для пиццы",
      PrIncludes2: "Кремовый соус",
      PrIncludes3: "Моцарелла",
      PrIncludes4: "Морепродукты (креветки, мидии, кальмары)",
    },
    {
      id: 36,
      quantity: 1,
      img: "FourCheesePizza",
      name: "Пицца 4 сыра",
      category: "Пицца",
      price: "579₽",
      Gram: "400г",
      desc: "Пицца с четырьмя видами сыра: моцарелла, пармезан, горгонзола и рикотта. Для настоящих сырных гурманов.",
      PrIncludes1: "Тесто для пиццы",
      PrIncludes2: "Томатный соус",
      PrIncludes3: "Моцарелла",
      PrIncludes4: "Пармезан",
      PrIncludes5: "Горгонзола",
      PrIncludes6: "Рикотта",
    },
    {
      id: 37,
      quantity: 1,
      img: "ChickenTeriyakiWok",
      name: "Вок с курицей терияки",
      category: "Вок",
      price: "449₽",
      Gram: "350г",
      desc: "Вок с кусочками куриного филе, овощами и соусом терияки. Вкусное и сытное блюдо для любителей восточной кухни.",
      PrIncludes1: "Куриное филе",
      PrIncludes2: "Овощи (перец, брокколи, морковь)",
      PrIncludes3: "Соус терияки",
      PrIncludes4: "Рис или лапша",
    },
    {
      id: 38,
      quantity: 1,
      img: "BeefBlackPepperWok",
      name: "Вок с говядиной и черным перцем",
      category: "Вок",
      price: "469₽",
      Gram: "350г",
      desc: "Вок с сочными кусочками говядины, овощами и соусом с черным перцем. Острота и насыщенный вкус.",
      PrIncludes1: "Говядина",
      PrIncludes2: "Овощи (перец, лук, грибы)",
      PrIncludes3: "Соус с черным перцем",
      PrIncludes4: "Рис или лапша",
    },
    {
      id: 39,
      quantity: 1,
      img: "VegetableWok",
      name: "Овощной вок",
      category: "Вок",
      price: "429₽",
      Gram: "300г",
      desc: "Вегетарианский вок с разнообразными овощами и соусом соевого соуса. Легкий и полезный выбор.",
      PrIncludes1: "Овощи (брокколи, морковь, перец, грибы)",
      PrIncludes2: "Соевый соус",
      PrIncludes3: "Рис или лапша",
    },
    {
      id: 40,
      quantity: 1,
      img: "ShrimpGarlicWok",
      name: "Вок с креветками и чесноком",
      category: "Вок",
      price: "489₽",
      Gram: "350г",
      desc: "Вок с креветками, чесноком и овощами, приготовленный в ароматном соусе. Отличный выбор для любителей морепродуктов.",
      PrIncludes1: "Креветки",
      PrIncludes2: "Овощи (брокколи, перец, морковь)",
      PrIncludes3: "Соус с чесноком",
      PrIncludes4: "Рис или лапша",
    },
    {
      id: 41,
      quantity: 1,
      img: "SpicyPorkWok",
      name: "Вок с острым свининой",
      category: "Вок",
      price: "459₽",
      Gram: "350г",
      desc: "Вок с кусочками свинины в остром соусе, с добавлением свежих овощей. Пикантное блюдо для любителей острого.",
      PrIncludes1: "Свинина",
      PrIncludes2: "Овощи (перец, лук, грибы)",
      PrIncludes3: "Острый соус",
      PrIncludes4: "Рис или лапша",
    },
    {
      id: 42,
      quantity: 1,
      img: "TofuWok",
      name: "Вок с тофу",
      category: "Вок",
      price: "439₽",
      Gram: "300г",
      desc: "Вок с тофу, овощами и соусом из соевого соуса. Веганский вариант для любителей здорового питания.",
      PrIncludes1: "Тофу",
      PrIncludes2: "Овощи (брокколи, морковь, перец)",
      PrIncludes3: "Соевый соус",
      PrIncludes4: "Рис или лапша",
    },
    {
      id: 43,
      quantity: 1,
      img: "ChocolateCake",
      name: "Шоколадный торт",
      category: "Десерты",
      price: "349₽",
      Gram: "300г",
      desc: "Насыщенный шоколадный торт с кремовой начинкой и шоколадной глазурью. Идеально для любителей шоколада.",
      PrIncludes1: "Шоколадное тесто",
      PrIncludes2: "Крем на основе сливок",
      PrIncludes3: "Шоколадная глазурь",
    },
    {
      id: 44,
      quantity: 1,
      img: "Cheesecake",
      name: "Чизкейк",
      category: "Десерты",
      price: "379₽",
      Gram: "250г",
      desc: "Нежный чизкейк с ванильной начинкой на ореховом корже. Подается с фруктовым соусом.",
      PrIncludes1: "Ванильный крем-сыр",
      PrIncludes2: "Ореховый корж",
      PrIncludes3: "Фруктовый соус (по выбору)",
    },
    {
      id: 45,
      quantity: 1,
      img: "Tiramisu",
      name: "Тирамису",
      category: "Десерты",
      price: "389₽",
      Gram: "250г",
      desc: "Классический тирамису с нежными слоями крема и кофе, посыпанный какао-порошком.",
      PrIncludes1: "Крем из маскарпоне",
      PrIncludes2: "Кофейные савоярди",
      PrIncludes3: "Какао-порошок",
    },
    {
      id: 46,
      quantity: 1,
      img: "FruitSalad",
      name: "Фруктовый салат",
      category: "Десерты",
      price: "299₽",
      Gram: "200г",
      desc: "Свежий фруктовый салат с медом и мятой. Легкий и освежающий десерт.",
      PrIncludes1: "Свежие фрукты (яблоки, апельсины, киви, бананы)",
      PrIncludes2: "Мед",
      PrIncludes3: "Мелко нарезанная мята",
    },
    {
      id: 47,
      quantity: 1,
      img: "LemonMeringuePie",
      name: "Лимонный пирог с меренгой",
      category: "Десерты",
      price: "359₽",
      Gram: "300г",
      desc: "Пирог с лимонной начинкой и легкой меренговой корочкой. Идеально для тех, кто любит кисло-сладкие десерты.",
      PrIncludes1: "Лимонная начинка",
      PrIncludes2: "Меренговая корочка",
      PrIncludes3: "Песочное тесто",
    },
    {
      id: 48,
      quantity: 1,
      img: "IceCreamSundae",
      name: "Мороженое Sundae",
      category: "Десерты",
      price: "329₽",
      Gram: "250г",
      desc: "Мороженое Sundae с шоколадным или карамельным соусом, посыпанное орехами и взбитыми сливками.",
      PrIncludes1: "Мороженое (ванильное или шоколадное)",
      PrIncludes2: "Шоколадный или карамельный соус",
      PrIncludes3: "Орехи",
      PrIncludes4: "Взбитые сливки",
    },
    {
      id: 49,
      quantity: 1,
      img: "Ketchup",
      name: "Кетчуп",
      category: "Соусы",
      price: "99₽",
      Gram: "150г",
      desc: "Классический кетчуп с томатным вкусом и легкой сладостью. Идеально подходит для бургеров, картошки фри и закусок.",
      PrIncludes1: "Томаты",
      PrIncludes2: "Сахар",
      PrIncludes3: "Уксус",
      PrIncludes4: "Специи",
    },
    {
      id: 50,
      quantity: 1,
      img: "Mayonnaise",
      name: "Майонез",
      category: "Соусы",
      price: "109₽",
      Gram: "150г",
      desc: "Кремовый майонез с насыщенным вкусом. Отлично подходит для салатов, сэндвичей и закусок.",
      PrIncludes1: "Яйцо",
      PrIncludes2: "Масло растительное",
      PrIncludes3: "Уксус",
      PrIncludes4: "Специи",
    },
    {
      id: 51,
      quantity: 1,
      img: "BarbecueSauce",
      name: "BBQ соус",
      category: "Соусы",
      price: "119₽",
      Gram: "150г",
      desc: "Соус BBQ с насыщенным вкусом дыма и специй. Отлично подходит для мяса, бургеров и гриля.",
      PrIncludes1: "Томаты",
      PrIncludes2: "Уксус",
      PrIncludes3: "Специи",
      PrIncludes4: "Кленовый сироп",
    },
    {
      id: 52,
      quantity: 1,
      img: "GarlicSauce",
      name: "Чесночный соус",
      category: "Соусы",
      price: "119₽",
      Gram: "150г",
      desc: "Ароматный чесночный соус с легкой кремовой текстурой. Отлично подходит для шаурмы, пиццы и овощей.",
      PrIncludes1: "Чеснок",
      PrIncludes2: "Сметана",
      PrIncludes3: "Майонез",
      PrIncludes4: "Лимонный сок",
    },
    {
      id: 53,
      quantity: 1,
      img: "SoySauce",
      name: "Соевый соус",
      category: "Соусы",
      price: "109₽",
      Gram: "150г",
      desc: "Классический соевый соус с насыщенным умами вкусом. Подходит для китайской кухни, суши и воков.",
      PrIncludes1: "Соевые бобы",
      PrIncludes2: "Пшеница",
      PrIncludes3: "Соль",
      PrIncludes4: "Ферментация",
    },
    {
      id: 54,
      quantity: 1,
      img: "HotSauce",
      name: "Острый соус",
      category: "Соусы",
      price: "119₽",
      Gram: "150г",
      desc: "Острый соус с насыщенным вкусом и пикантной остротой. Отлично подходит для любителей острых блюд и закусок.",
      PrIncludes1: "Перцы чили",
      PrIncludes2: "Уксус",
      PrIncludes3: "Соль",
      PrIncludes4: "Специи",
    },
  ]);
  const [selectedCategory, setSelectedCategory] = useState("Все");

  const [cart, setCart] = useState([]);

  const addToCart = (product) => {
    setCart((prevCart) => {
      const existingProduct = prevCart.find((item) => item.id === product.id);

      if (existingProduct) {
        return prevCart.map((item) =>
          item.id === product.id
            ? { ...item, quantity: item.quantity + 1 }
            : item
        );
      } else {
        return [...prevCart, { ...product, quantity: 1 }];
      }
    });
  };

  const filteresByCategori = (category) => {
    setSelectedCategory(category);
  };
  return (
    <MyContext.Provider
      value={{
        MenuMassiv,
        setMenuMassiv,
        selectedCategory,
        setSelectedCategory,
        filteresByCategori,
        cart,
        setCart,
        addToCart,
      }}
    >
      {children}
    </MyContext.Provider>
  );
};

export const useMyContext = () => {
  const context = useContext(MyContext);
  if (!context) {
    throw new Error("useMyContext должен использоваться внутри MyProvider");
  }
  return context;
};
